// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SurveysApi.Data;

#nullable disable

namespace SurveysApi.Migrations
{
    [DbContext(typeof(MiDbContext))]
    [Migration("20260620004100_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SurveysApi.DbModels.Answered", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<string>("data_surveys")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("date_end")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("date_start")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("survey_id")
                        .HasColumnType("integer");

                    b.Property<int?>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id")
                        .HasName("answered_pk");

                    b.HasIndex("survey_id");

                    b.HasIndex("user_id");

                    b.ToTable("Answered", (string)null);
                });

            modelBuilder.Entity("SurveysApi.DbModels.Question", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<string>("ask")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("options")
                        .HasColumnType("text");

                    b.Property<int>("required")
                        .HasColumnType("integer");

                    b.Property<int?>("surveys_id")
                        .HasColumnType("integer");

                    b.Property<string>("type_ask")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("id")
                        .HasName("questions_pk");

                    b.HasIndex("surveys_id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("SurveysApi.DbModels.Survey", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<string>("date_register")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id")
                        .HasName("surveys_pk");

                    b.HasIndex(new[] { "name" }, "surveys_pk_2")
                        .IsUnique();

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("SurveysApi.DbModels.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("user_rol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id")
                        .HasName("users_pk");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SurveysApi.DbModels.Answered", b =>
                {
                    b.HasOne("SurveysApi.DbModels.Survey", "survey")
                        .WithMany("Answereds")
                        .HasForeignKey("survey_id")
                        .HasConstraintName("surveyanswered_surveys_id_fk");

                    b.HasOne("SurveysApi.DbModels.User", "user")
                        .WithMany("Answereds")
                        .HasForeignKey("user_id")
                        .HasConstraintName("surveyanswered_users_id_fk");

                    b.Navigation("survey");

                    b.Navigation("user");
                });

            modelBuilder.Entity("SurveysApi.DbModels.Question", b =>
                {
                    b.HasOne("SurveysApi.DbModels.Survey", "surveys")
                        .WithMany("Questions")
                        .HasForeignKey("surveys_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("questions_ surveys_id_fk");

                    b.Navigation("surveys");
                });

            modelBuilder.Entity("SurveysApi.DbModels.Survey", b =>
                {
                    b.Navigation("Answereds");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("SurveysApi.DbModels.User", b =>
                {
                    b.Navigation("Answereds");
                });
#pragma warning restore 612, 618
        }
    }
}
